In [49]:
import torch
from torch import nn
print(torch.__version__)

1.7.0+cu110


# Containers

## MODULEDICT

In [50]:
K = 2
in_features = 256
out_features = 384

submodules = nn.ModuleDict({
                str(k): nn.Linear(in_features=in_features, out_features=out_features, bias=False) for k in range(K) 
        })
       
print(submodules)

ModuleDict(
  (0): Linear(in_features=256, out_features=384, bias=False)
  (1): Linear(in_features=256, out_features=384, bias=False)
)


In [51]:
submodules['0']

Linear(in_features=256, out_features=384, bias=False)

In [52]:
submodules['1']

Linear(in_features=256, out_features=384, bias=False)

In [53]:
submodules.items()

odict_items([('0', Linear(in_features=256, out_features=384, bias=False)), ('1', Linear(in_features=256, out_features=384, bias=False))])

## PARAMETERDICT

In [54]:
in_features = 2
out_features = 3
dropout = nn.Dropout(p=0.2)

W = nn.Parameter(torch.zeros(size=(in_features, out_features), dtype=torch.float))
nn.init.xavier_uniform_(W.data, gain=1.414)


W1 = nn.Parameter(torch.zeros(size=(in_features, out_features), dtype=torch.float))
nn.init.xavier_uniform_(W1.data, gain=1.414)

print("W:", W)
print("W1:", W1)

W: Parameter containing:
tensor([[ 0.5367, -1.0012,  0.1146],
        [ 0.5775,  0.2551,  1.0153]], requires_grad=True)
W1: Parameter containing:
tensor([[ 0.2246,  1.1879,  0.0477],
        [-1.0705, -1.2040,  1.3738]], requires_grad=True)


### Initial Weight Matrices

In [55]:
in_features = 2
out_features = 3
K = 3
dropout = nn.Dropout(p=0.2)

W_0 = nn.ParameterDict({})

for k in range(K):
    weight_matrix = nn.Parameter(torch.zeros(size=(in_features, out_features), dtype=torch.float))
    nn.init.xavier_uniform_(weight_matrix.data, gain=1.414)
    W_0.update({str(k): weight_matrix})


for k in range(K):
    print("W_0:", W_0[str(k)])

W_0: Parameter containing:
tensor([[ 0.2756,  1.0208, -1.5280],
        [ 0.4719, -1.3388,  0.9247]], requires_grad=True)
W_0: Parameter containing:
tensor([[-1.4721, -0.0601, -0.2508],
        [ 0.7537,  0.8154,  0.6244]], requires_grad=True)
W_0: Parameter containing:
tensor([[ 0.5841,  1.4456,  1.0069],
        [-1.1005,  0.7155, -0.2154]], requires_grad=True)


### Deeper Weight Matrices

In [56]:
in_features = 2
out_features = 3
K = 3
dropout = nn.Dropout(p=0.2)

W = nn.ParameterDict({})

for k in range(K):
    weight_matrix = nn.Parameter(torch.zeros(size=(out_features, out_features), dtype=torch.float))
    nn.init.xavier_uniform_(weight_matrix.data, gain=1.414)
    W.update({str(k): weight_matrix})


for k in range(K):
    print("W:", W[str(k)])

W: Parameter containing:
tensor([[ 1.0805,  0.4907, -0.5316],
        [ 0.5271,  1.1622,  0.4409],
        [ 1.3866,  0.6420, -0.5513]], requires_grad=True)
W: Parameter containing:
tensor([[-0.7180,  0.7325,  0.9964],
        [-0.6868,  1.1877, -0.2066],
        [ 0.0638,  1.1374,  0.3401]], requires_grad=True)
W: Parameter containing:
tensor([[-0.0647,  0.9215, -0.4554],
        [ 1.3577,  0.3805,  0.0052],
        [ 1.3263,  0.6866,  0.2499]], requires_grad=True)


### V

In [57]:
in_features = 2
out_features = 3
K = 3
dropout = nn.Dropout(p=0.2)

V = nn.ParameterDict({})

for k in range(K):
    weight_matrix = nn.Parameter(torch.zeros(size=(out_features, out_features), dtype=torch.float))
    nn.init.xavier_uniform_(weight_matrix.data, gain=1.414)
    V.update({str(k): weight_matrix})


for k in range(K):
    print("V:", V[str(k)])

V: Parameter containing:
tensor([[-0.5614, -0.6842, -0.8585],
        [ 0.4292,  0.5178, -0.0989],
        [-0.4743, -1.2789, -0.2739]], requires_grad=True)
V: Parameter containing:
tensor([[-0.5420,  0.0748,  0.0246],
        [-1.3938,  0.4892,  0.9746],
        [ 0.1958, -0.0764,  0.2099]], requires_grad=True)
V: Parameter containing:
tensor([[-0.1162, -0.5148,  0.5048],
        [ 0.3429, -0.3878,  0.1285],
        [ 1.4073, -1.3754,  0.5097]], requires_grad=True)
