In [1]:
import torch
from torch import nn
print(torch.__version__)

1.11.0


# TORCH

## TORCH.POW

In [2]:
A = torch.randint(low=2, high=7, size=(3,))
print("A:", A)

result = torch.pow(A, 2)
print("result:", result)

A: tensor([4, 6, 6])
result: tensor([16, 36, 36])


## TORCH.CLAMP

In [3]:
A = torch.randn(4)
print("A:", A)

torch.clamp(A, min=-0.5, max=0.5)


A: tensor([ 1.2523, -0.9718, -1.0578, -1.1109])


tensor([ 0.5000, -0.5000, -0.5000, -0.5000])

## TORCH.TRIU

In [4]:
A = torch.randn(3, 3)
print("A:", A)

A: tensor([[-0.6096,  0.3587,  0.9665],
        [ 1.0254,  1.3564,  1.1744],
        [-0.4966, -0.8655,  0.0188]])


In [5]:
torch.triu(A)

tensor([[-0.6096,  0.3587,  0.9665],
        [ 0.0000,  1.3564,  1.1744],
        [ 0.0000,  0.0000,  0.0188]])

In [6]:
torch.triu(A, diagonal=0)

tensor([[-0.6096,  0.3587,  0.9665],
        [ 0.0000,  1.3564,  1.1744],
        [ 0.0000,  0.0000,  0.0188]])

In [7]:
torch.triu(A, diagonal=1)

tensor([[0.0000, 0.3587, 0.9665],
        [0.0000, 0.0000, 1.1744],
        [0.0000, 0.0000, 0.0000]])

In [13]:
x = torch.triu(A, diagonal=1)
y = x.T
print("x:", x)
print("y:", y)

x: tensor([[0.0000, 0.3587, 0.9665],
        [0.0000, 0.0000, 1.1744],
        [0.0000, 0.0000, 0.0000]])
y: tensor([[0.0000, 0.0000, 0.0000],
        [0.3587, 0.0000, 0.0000],
        [0.9665, 1.1744, 0.0000]])


In [8]:
torch.triu(A, diagonal=2)

tensor([[0.0000, 0.0000, 0.9665],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [9]:
torch.triu(A, diagonal=-1)

tensor([[-0.6096,  0.3587,  0.9665],
        [ 1.0254,  1.3564,  1.1744],
        [ 0.0000, -0.8655,  0.0188]])

## TORCH.TRIL

In [14]:
A = torch.randn(3, 3)
print("A:", A)

A: tensor([[-0.3782,  0.6845,  0.3236],
        [ 0.4145,  0.5247,  1.7879],
        [ 1.2359, -0.4351, -0.3029]])


In [15]:
torch.tril(A)

tensor([[-0.3782,  0.0000,  0.0000],
        [ 0.4145,  0.5247,  0.0000],
        [ 1.2359, -0.4351, -0.3029]])

In [17]:
torch.tril(A, diagonal=-1)

tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.4145,  0.0000,  0.0000],
        [ 1.2359, -0.4351,  0.0000]])

## TORCH.MATRIX_POWER
Sometimes, we may need to get a tensor raised to a specific power n. For example, we may need to get the tensor with power of n = 2 or more. In this case, the function torch.matrix_power() is very helpful. Note that if the value of n is negative, the function will return the inverse of the tensor raised to the power n. Also, the matrix has to be a square matrix with size (m,m)

In [10]:
A = torch.randint(8, (3, 3))
print("A:\n", A)

A:
 tensor([[7, 7, 5],
        [3, 3, 4],
        [1, 6, 6]])


In [11]:
print("A^0", torch.matrix_power(A, 0))

A^0 tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])


In [13]:
print("A^1", torch.matrix_power(A, 1))

A^0 tensor([[7, 7, 5],
        [3, 3, 4],
        [1, 6, 6]])


In [14]:
print("A^2", torch.matrix_power(A, 2))

A^2 tensor([[ 75, 100,  93],
        [ 34,  54,  51],
        [ 31,  61,  65]])
