In [2]:
import torch
from torch import nn
print(torch.__version__)

1.11.0


# TORCH

## TORCH.POW

In [2]:
A = torch.randint(low=2, high=7, size=(3,))
print("A:", A)

result = torch.pow(A, 2)
print("result:", result)

A: tensor([2, 4, 6])
result: tensor([ 4, 16, 36])


## TORCH.CLAMP

In [7]:
A = torch.randn(4)
print("A:", A)

torch.clamp(A, min=-0.5, max=0.5)


A: tensor([-0.2475, -0.5333, -0.0557, -0.9554])


tensor([-0.2475, -0.5000, -0.0557, -0.5000])

## TORCH.TRIU

In [3]:
A = torch.randn(3, 3)
print("A:", A)

A: tensor([[ 0.6271, -1.5570, -0.3644],
        [-0.0268, -0.5251, -0.4088],
        [ 1.1846, -0.0268,  0.2569]])


In [4]:
torch.triu(A)

tensor([[ 0.6271, -1.5570, -0.3644],
        [ 0.0000, -0.5251, -0.4088],
        [ 0.0000,  0.0000,  0.2569]])

In [5]:
torch.triu(A, diagonal=0)

tensor([[ 0.6271, -1.5570, -0.3644],
        [ 0.0000, -0.5251, -0.4088],
        [ 0.0000,  0.0000,  0.2569]])

In [6]:
torch.triu(A, diagonal=1)

tensor([[ 0.0000, -1.5570, -0.3644],
        [ 0.0000,  0.0000, -0.4088],
        [ 0.0000,  0.0000,  0.0000]])

In [7]:
torch.triu(A, diagonal=2)

tensor([[ 0.0000,  0.0000, -0.3644],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])