In [53]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import dgl
import dgl.function as fn
import math

from dgl.nn.pytorch.glob import AvgPooling

# Querying Graph Structure

## dgl.DGLGraph.in_degrees

In [54]:
G = dgl.DGLGraph()
G.add_nodes(3)

print("G:", G)

G: Graph(num_nodes=3, num_edges=0,
      ndata_schemes={}
      edata_schemes={})


/home/zayed/anaconda3/envs/arma_dgl/lib/python3.8/site-packages/dgl/heterograph.py:72: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning('Recommend creating graphs by `dgl.graph(data)`'


In [55]:
G.add_edges([0, 0, 1, 1], [1, 2, 2, 0])   # (0, 1), (0, 2), (1, 2)
print("G:", G)

G: Graph(num_nodes=3, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


In [56]:
inDegreeArray = G.in_degrees().float()
print("In-degree Array:", inDegreeArray)

In-degree Array: tensor([1., 1., 2.])


In [57]:
inDegreeArray.clamp(min=1)

tensor([1., 1., 2.])

In [58]:
norm = torch.pow(inDegreeArray, -0.5)
print(norm)

tensor([1.0000, 1.0000, 0.7071])


In [59]:
norm.unsqueeze(1)

tensor([[1.0000],
        [1.0000],
        [0.7071]])

In [63]:
print("norm.shape:", norm.shape)

norm.shape: torch.Size([3])
